require 'more_core_extensions/version'

require 'more_core_extensions/core_ext/array'
require 'more_core_extensions/core_ext/benchmark'
require 'more_core_extensions/core_ext/class'
require 'more_core_extensions/core_ext/hash'
require 'more_core_extensions/core_ext/math'
require 'more_core_extensions/core_ext/module'
require 'more_core_extensions/core_ext/numeric'
require 'more_core_extensions/core_ext/object'
require 'more_core_extensions/core_ext/range'
require 'more_core_extensions/core_ext/string'
require 'more_core_extensions/core_ext/symbol'
